### ISSUE TITLE
Use RPiPlay as a meson subproject

### ISSUE THREAD

**Issue by hadess** [knuesel/gst-airplay#4]
meson knows how to use subproject through wrap files, and has a compatibility module that allows building cmake subprojects.

This would make it easier to build this project, pass the right options, etc.

See https://mesonbuild.com/CMake-module.html

**Comment by sijow** [comment]
That would be nice! I gave it a shot on the `wrap-rpiplay` branch. But it seems meson doesn't pick up the public headers and link libraries declared in `lib/CMakeLists.txt` from the RPiPlay project. A PR is welcome if you know how to fix it :)

**Comment by hadess** [comment]
That seems to work:
https://github.com/hadess/gst-airplay/commit/96db4f2909a1ce1613a5e5be22a09c447cdc770d

rpiplay should really be using the `airplay` as the directory name to put all its sources if that's the name it's going to use when installed. The rest is mostly meson/CMake integration not being great, especially when half the libraries are supposed to be static which is icky. It's still installing the .a files for llhttp and stuff, which I have no idea how to disable...

**Comment by hadess** [comment]
FWIW, the way that the [wrapdb](https://github.com/mesonbuild/wrapdb) would fix this would be by providing a meson.build file to build rpiairplay.

**Comment by sijow** [comment]
Thanks!

Looks like this doesn't find libdns_sd on my Ubuntu-based system, and doesn't link pthread. I could fix it like this: 022b6a8d

But I guess it won't work for you then? It would be nice to have something that works for all major distros...

**Comment by hadess** [comment]
> Looks like this doesn't find libdns_sd on my Ubuntu-based system, and doesn't link pthread. I could fix it like this: [022b6a8](https://github.com/knuesel/gst-airplay/commit/022b6a8d14cb027fb9d2ca9226b6361a8044fde9)

The avahi packaging in Fedora has both pkg-config file, the bare `libdns_sd` is a Fedora addition:
https://src.fedoraproject.org/rpms/avahi/blob/rawhide/f/avahi.spec#_521

I didn't have any problems linking to libpthread in my version, or with just the `avahi-compat-libdns_sd` change you made.

**Comment by sijow** [comment]
Excellent, I'll merge this in main then!

Regarding the RPiPlay directory name: the thing is the original project just wants to make the `rpiplay` executable. Since it happens to have internally the best AirPlay implementation I could find, I made a couple of changes to have the CMake project also export a library for other projects to use. I guess the proper fix would be to split RPiPlay into two separate projects (then the library could be wrapdb'ed)...

For the libraries: I thought having all internal libraries statically linked might make it harder to write the build scripts but then the result is more user friendly: just one file to distribute and install in `.local/share/gstreamer-1.0/plugins/`), compared to messing with `/usr/local` or `LD_LIBRARY_PATH`. (I guess having proper packages for all the libs would be nice but I wouldn't want to make and maintain that).

I just pushed a commit on the `wrap-rpiplay` branch that should disable the installation of `.a` files.

**Comment by sijow** [comment]
Sorry, now it's pushed. If that works for you I'll merge it in main.

**Comment by hadess** [comment]
> I just pushed a commit on the `wrap-rpiplay` branch that should disable the installation of `.a` files.

Works great:
```
jhbuild uninstall gst-airplay
I: module "gst-airplay" does not exist, created automatically using repository "gitlab.gnome.org/GNOME"
I: Deleted: '/home/hadess/Projects/gnome-install/lib/gstreamer-1.0/libgstairplay.so'
```

**Comment by sijow** [comment]
Thanks again.
